import type { LegalContentDocument } from "@/content/shared/document-types"

export const englishLegalDocuments = [
  {
    id: "legal.software-license",
    slug: "software-license",
    locale: "en",
    title: "Software license",
    summary: "Explains the separation between GPL-covered theme rights and official commercial services.",
    documentType: "SOFTWARE_LICENSE",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/catalog",
    relatedLinks: ["/en/docs/activation", "/en/docs/updates", "/en/legal/commercial-terms"],
    sections: [
      {
        id: "separation",
        title: "Separate layers",
        body: [
          "The distributed WordPress/WooCommerce theme code should remain compatible with GPL rights.",
          "Commercial purchase provides access to official downloads, updates, support and approved services.",
        ],
      },
      {
        id: "license-key",
        title: "Technical key role",
        body: [
          "The key controls official platform services, not the rights already granted over received code.",
          "Expired access must not be described as disabling the customer's existing storefront.",
        ],
      },
    ],
  },
  {
    id: "legal.commercial-terms",
    slug: "commercial-terms",
    locale: "en",
    title: "Commercial terms",
    summary: "Review structure for purchase, delivery and official access terms.",
    documentType: "COMMERCIAL_TERMS",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/commerce",
    relatedLinks: ["/en/pricing", "/en/legal/software-license", "/en/legal/refunds"],
    sections: [
      {
        id: "scope",
        title: "Approval scope",
        body: [
          "This page reserves sections for purchase, renewal, suspension and version acceptance.",
          "No duration, jurisdiction, limitation or promise is final before legal review.",
        ],
      },
    ],
  },
  {
    id: "legal.support-policy",
    slug: "support-policy",
    locale: "en",
    title: "Support policy",
    summary: "Documentation framework for Starter, Pro and Managed support without final SLA commitment.",
    documentType: "SUPPORT_POLICY",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "PRODUCT_REVIEW",
    visibility: "public",
    owner: "support/services",
    relatedLinks: ["/en/docs/troubleshooting", "/en/offers/pro", "/en/offers/managed"],
    sections: [
      {
        id: "boundaries",
        title: "Support boundaries",
        body: [
          "Official support covers services, updates and flows approved by the active offer.",
          "Hosting, third-party payment and customer content incidents must be separated from product defects.",
        ],
      },
    ],
  },
  {
    id: "legal.refunds",
    slug: "refunds",
    locale: "en",
    title: "Refund policy",
    summary: "Review placeholder for refund conditions without a final commercial promise.",
    documentType: "REFUNDS",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/commerce",
    relatedLinks: ["/en/pricing", "/en/legal/commercial-terms"],
    sections: [
      {
        id: "review",
        title: "Decision required",
        body: [
          "Criteria after download, started service or Managed configuration remain subject to approval.",
          "The page must not display a refund commitment before business and legal validation.",
        ],
      },
    ],
  },
  {
    id: "legal.privacy",
    slug: "privacy",
    locale: "en",
    title: "Privacy",
    summary: "Collection and retention structure to complete before production.",
    documentType: "PRIVACY",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/auth",
    relatedLinks: ["/en/register", "/en/account/settings/security"],
    sections: [
      {
        id: "data",
        title: "Data to map",
        body: [
          "Account, payment, entitlement, license and support data must be listed before launch.",
          "IP address or user-agent capture for acceptance remains blocked until privacy approval.",
        ],
      },
    ],
  },
  {
    id: "legal.trademark",
    slug: "trademark",
    locale: "en",
    title: "Trademarks and identity",
    summary: "Review framework for brand, logo and product screenshot usage.",
    documentType: "TRADEMARK",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/brand",
    relatedLinks: ["/en/legal/software-license"],
    sections: [
      {
        id: "usage",
        title: "Usage to approve",
        body: [
          "Code rights do not automatically approve commercial use of marks or logos.",
          "Naming, screenshots and co-branding permissions must be specified before publication.",
        ],
      },
    ],
  },
] satisfies LegalContentDocument[]
