import type { LegalContentDocument } from "@/content/shared/document-types"

export const frenchLegalDocuments = [
  {
    id: "legal.software-license",
    slug: "software-license",
    locale: "fr",
    title: "Licence logicielle",
    summary: "Explique la separation entre les droits GPL du theme et l'acces commercial aux services officiels.",
    documentType: "SOFTWARE_LICENSE",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/catalog",
    relatedLinks: ["/fr/docs/activation", "/fr/docs/updates", "/fr/legal/commercial-terms"],
    sections: [
      {
        id: "separation",
        title: "Deux couches distinctes",
        body: [
          "Le code du theme WordPress/WooCommerce distribue doit rester compatible avec les droits attaches a la GPL.",
          "L'achat commercial donne acces aux telechargements officiels, aux mises a jour, au support et aux services approuves.",
        ],
      },
      {
        id: "license-key",
        title: "Role de la cle technique",
        body: [
          "La cle controle l'acces aux services officiels de la plateforme, pas les droits deja accordes sur le code recu.",
          "Une expiration d'acces ne doit pas etre presentee comme une desactivation du site existant du client.",
        ],
      },
    ],
  },
  {
    id: "legal.commercial-terms",
    slug: "commercial-terms",
    locale: "fr",
    title: "Conditions commerciales",
    summary: "Structure de revue pour les conditions d'achat, de livraison et d'acces officiel.",
    documentType: "COMMERCIAL_TERMS",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/commerce",
    relatedLinks: ["/fr/pricing", "/fr/legal/software-license", "/fr/legal/refunds"],
    sections: [
      {
        id: "scope",
        title: "Perimetre a approuver",
        body: [
          "Cette page reserve les rubriques d'achat, de renouvellement, de suspension et d'acceptation de version.",
          "Aucune duree, juridiction, limitation ou promesse n'est definitive avant validation juridique.",
        ],
      },
    ],
  },
  {
    id: "legal.support-policy",
    slug: "support-policy",
    locale: "fr",
    title: "Politique de support",
    summary: "Cadre de documentation pour Starter, Pro et Managed sans engagement SLA final.",
    documentType: "SUPPORT_POLICY",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "PRODUCT_REVIEW",
    visibility: "public",
    owner: "support/services",
    relatedLinks: ["/fr/docs/troubleshooting", "/fr/offers/pro", "/fr/offers/managed"],
    sections: [
      {
        id: "boundaries",
        title: "Frontieres de support",
        body: [
          "Le support officiel couvre les services, mises a jour et parcours approuves par l'offre active.",
          "Les incidents d'hebergement, de paiement tiers ou de contenu client doivent etre distingues des defauts produit.",
        ],
      },
    ],
  },
  {
    id: "legal.refunds",
    slug: "refunds",
    locale: "fr",
    title: "Politique de remboursement",
    summary: "Placeholder de revue pour les conditions de remboursement, sans promesse commerciale finale.",
    documentType: "REFUNDS",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/commerce",
    relatedLinks: ["/fr/pricing", "/fr/legal/commercial-terms"],
    sections: [
      {
        id: "review",
        title: "Decision requise",
        body: [
          "Les criteres apres telechargement, service commence ou configuration Managed restent a approuver.",
          "La page ne doit pas afficher d'engagement de remboursement avant validation business et juridique.",
        ],
      },
    ],
  },
  {
    id: "legal.privacy",
    slug: "privacy",
    locale: "fr",
    title: "Confidentialite",
    summary: "Structure de collecte et conservation a completer avant production.",
    documentType: "PRIVACY",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/auth",
    relatedLinks: ["/fr/register", "/fr/account/settings/security"],
    sections: [
      {
        id: "data",
        title: "Donnees a cartographier",
        body: [
          "Les donnees de compte, paiement, entitlement, licence et support doivent etre listees avant lancement.",
          "La capture d'adresse IP ou user-agent pour acceptation reste bloquee jusqu'a approbation vie privee.",
        ],
      },
    ],
  },
  {
    id: "legal.trademark",
    slug: "trademark",
    locale: "fr",
    title: "Marques et identite",
    summary: "Cadre de revue pour l'usage des marques, noms, logos et captures produit.",
    documentType: "TRADEMARK",
    version: "0.1.0-draft",
    effectiveDate: null,
    lastReviewedAt: "2026-07-15",
    reviewStatus: "LEGAL_REVIEW",
    visibility: "public",
    owner: "legal/brand",
    relatedLinks: ["/fr/legal/software-license"],
    sections: [
      {
        id: "usage",
        title: "Usage a approuver",
        body: [
          "Les droits sur le code ne valident pas automatiquement l'usage commercial des marques ou logos.",
          "Les permissions de nommage, screenshots et co-branding doivent etre precisees avant publication.",
        ],
      },
    ],
  },
] satisfies LegalContentDocument[]
