"use client"

import { useMemo, useState } from "react"

import { Alert } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { FormField } from "@/components/ui/form-field"
import { Input } from "@/components/ui/input"
import { Cluster } from "@/components/ui/layout"
import { Select } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import type { Locale } from "@/src/i18n/locales"

type Endpoint = "activate" | "validate" | "deactivate"

type ApiState = {
  status: number | null
  body: unknown
  error: string | null
  endpoint: Endpoint | null
}

const defaultInstallationId = "6df54c7c-e60a-4e31-8bdc-4ecf3b22bc4b"

export function LicenseApiWorkbench({ locale }: { locale: Locale }) {
  const isFrench = locale === "fr"
  const [licenseKey, setLicenseKey] = useState("")
  const [installationId, setInstallationId] = useState(defaultInstallationId)
  const [siteUrl, setSiteUrl] = useState("https://shop.example.test")
  const [environment, setEnvironment] = useState<"PRODUCTION" | "STAGING">("PRODUCTION")
  const [productSlug, setProductSlug] = useState("woo-app-theme")
  const [themeVersion, setThemeVersion] = useState("1.0.0")
  const [result, setResult] = useState<ApiState>({ status: null, body: null, error: null, endpoint: null })
  const [loadingEndpoint, setLoadingEndpoint] = useState<Endpoint | null>(null)

  const payload = useMemo(
    () => ({
      licenseKey,
      installationId,
      siteUrl,
      environment,
      productSlug,
      themeVersion,
    }),
    [environment, installationId, licenseKey, productSlug, siteUrl, themeVersion],
  )

  async function callEndpoint(endpoint: Endpoint) {
    setLoadingEndpoint(endpoint)
    setResult({ status: null, body: null, error: null, endpoint })

    try {
      const endpointPayload = endpoint === "deactivate" ? withoutThemeVersion(payload) : payload
      const response = await fetch(`/api/licenses/${endpoint}`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Accept: "application/json",
          "X-TEP-Protocol": "1",
        },
        body: JSON.stringify(endpointPayload),
      })
      const body = (await response.json()) as unknown
      setResult({ status: response.status, body, error: null, endpoint })
    } catch (error) {
      setResult({
        status: null,
        body: null,
        error: error instanceof Error ? error.message : "Unknown request failure",
        endpoint,
      })
    } finally {
      setLoadingEndpoint(null)
    }
  }

  return (
    <section className="grid min-w-0 gap-6">
      <header className="rounded-xl border border-brand-border bg-white p-4 shadow-subtle sm:p-6">
        <Cluster>
          <Badge variant="orange">API V1</Badge>
          <Badge variant="outline">admin workbench</Badge>
          <Badge variant="outline">protocol header required</Badge>
        </Cluster>
        <h1 className="mt-5 font-heading text-2xl font-extrabold sm:text-3xl">
          {isFrench ? "Atelier API licences" : "License API workbench"}
        </h1>
        <p className="mt-3 max-w-3xl leading-7 text-brand-slate">
          {isFrench
            ? "Interface admin pour tester activate, validate et deactivate avec une cle de developpement generee par le seed."
            : "Admin interface for testing activate, validate and deactivate with a development key generated by the seed."}
        </p>
      </header>

      <Alert variant="info">
        {isFrench
          ? "Ordre de test conseille: activate, puis validate avec le meme Installation ID, Site URL et environnement. Apres deactivate, validate doit echouer tant que l'installation n'est pas reactivee."
          : "Recommended test order: activate, then validate with the same Installation ID, Site URL and environment. After deactivate, validate must fail until the installation is activated again."}
      </Alert>

      <div className="grid min-w-0 gap-6 xl:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
        <Card>
          <CardHeader>
            <CardTitle>{isFrench ? "Requete" : "Request"}</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4">
            <FormField
              hint={isFrench ? "Exemple: TEP1-.... genere par SEED_DEV_LICENSE=true pnpm db:seed" : "Example: TEP1-.... generated by SEED_DEV_LICENSE=true pnpm db:seed"}
              htmlFor="licenseKey"
              label={isFrench ? "Cle licence" : "License key"}
            >
              <Input
                autoComplete="off"
                id="licenseKey"
                onChange={(event) => setLicenseKey(event.target.value)}
                placeholder="TEP1-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX-XXXX"
                value={licenseKey}
              />
            </FormField>
            <div className="grid gap-4 md:grid-cols-2">
              <FormField htmlFor="installationId" label="Installation ID">
                <Input id="installationId" onChange={(event) => setInstallationId(event.target.value)} value={installationId} />
              </FormField>
              <FormField htmlFor="environment" label={isFrench ? "Environnement" : "Environment"}>
                <Select
                  id="environment"
                  onChange={(event) => setEnvironment(event.target.value as "PRODUCTION" | "STAGING")}
                  value={environment}
                >
                  <option value="PRODUCTION">PRODUCTION</option>
                  <option value="STAGING">STAGING</option>
                </Select>
              </FormField>
            </div>
            <Cluster className="items-stretch">
              <Button className="w-full sm:w-auto" onClick={() => setInstallationId(crypto.randomUUID())} size="compact" type="button" variant="ghost">
                {isFrench ? "Nouvel Installation ID" : "New Installation ID"}
              </Button>
            </Cluster>
            <FormField htmlFor="siteUrl" label="Site URL">
              <Input id="siteUrl" onChange={(event) => setSiteUrl(event.target.value)} value={siteUrl} />
            </FormField>
            <div className="grid gap-4 md:grid-cols-2">
              <FormField htmlFor="productSlug" label="Product slug">
                <Input id="productSlug" onChange={(event) => setProductSlug(event.target.value)} value={productSlug} />
              </FormField>
              <FormField htmlFor="themeVersion" label="Theme version">
                <Input id="themeVersion" onChange={(event) => setThemeVersion(event.target.value)} value={themeVersion} />
              </FormField>
            </div>
            <Cluster className="items-stretch">
              {(["activate", "validate", "deactivate"] satisfies Endpoint[]).map((endpoint) => (
                <Button
                  className="w-full sm:w-auto"
                  disabled={!licenseKey || loadingEndpoint !== null}
                  isLoading={loadingEndpoint === endpoint}
                  key={endpoint}
                  onClick={() => void callEndpoint(endpoint)}
                  type="button"
                  variant={endpoint === "deactivate" ? "outline" : "primary"}
                >
                  {endpointLabel(endpoint, isFrench)}
                </Button>
              ))}
            </Cluster>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>{isFrench ? "Reponse brute" : "Raw response"}</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4">
            <div className="flex flex-wrap gap-2">
              <Badge variant={result.status && result.status < 300 ? "success" : result.status ? "destructive" : "secondary"}>
                HTTP {result.status ?? "-"}
              </Badge>
              <Badge variant="outline">X-TEP-Protocol: 1</Badge>
            </div>
            {result.error ? <Alert variant="danger">{result.error}</Alert> : null}
            {isInvalidValidateResult(result) ? (
              <Alert variant="warning">
                {isFrench
                  ? "Validate cherche une activation ACTIVE existante. Relance activate avec exactement les memes champs, puis validate avant deactivate."
                  : "Validate looks for an existing ACTIVE activation. Run activate again with exactly the same fields, then validate before deactivate."}
              </Alert>
            ) : null}
            <Textarea
              className="min-h-[20rem] overflow-x-auto font-mono text-xs sm:min-h-[28rem]"
              readOnly
              value={result.body ? JSON.stringify(result.body, null, 2) : ""}
            />
          </CardContent>
        </Card>
      </div>
    </section>
  )
}

function endpointLabel(endpoint: Endpoint, isFrench: boolean) {
  if (endpoint === "activate") return isFrench ? "1. activer" : "1. activate"
  if (endpoint === "validate") return isFrench ? "2. valider" : "2. validate"
  return isFrench ? "3. desactiver" : "3. deactivate"
}

function isInvalidValidateResult(result: ApiState) {
  if (result.endpoint !== "validate" || !result.body || typeof result.body !== "object") return false
  const error = "error" in result.body ? result.body.error : null
  return Boolean(error && typeof error === "object" && "code" in error && error.code === "INVALID_LICENSE")
}

function withoutThemeVersion(payload: {
  environment: string
  installationId: string
  licenseKey: string
  productSlug: string
  siteUrl: string
  themeVersion: string
}) {
  return {
    licenseKey: payload.licenseKey,
    installationId: payload.installationId,
    siteUrl: payload.siteUrl,
    environment: payload.environment,
    productSlug: payload.productSlug,
  }
}
